#!/usr/bin/env php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

require __DIR__ . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

$codeGeneratorBinaryRequest = file_get_contents('php://stdin');
//$codeGeneratorBinaryRequest = file_get_contents('/tmp/gg.txt');

$templatesPath = __DIR__ . DIRECTORY_SEPARATOR . 'templates';
$output = __DIR__ . DIRECTORY_SEPARATOR . 'output';

$compiler = new Magento\ProtoGen\Compiler($templatesPath, $output);
$compiler->run($codeGeneratorBinaryRequest);

exit(0);