#!/usr/bin/env php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

require __DIR__ . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

$codeGeneratorBinaryRequest = file_get_contents('php://stdin');

$templatesPath = __DIR__  . '/templates';

$compiler = new Magento\ProtoGen\Compiler($templatesPath);
$compiler->run($codeGeneratorBinaryRequest);

exit(0);