<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptor.proto

namespace Google\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes a method of a service.
 *
 * Generated from protobuf message <code>google.protobuf.MethodDescriptorProto</code>
 */
class MethodDescriptorProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Input and output type names.  These are resolved in the same way as
     * FieldDescriptorProto.type_name, but must refer to a message type.
     *
     * Generated from protobuf field <code>string input_type = 2;</code>
     */
    protected $input_type = '';
    /**
     * Generated from protobuf field <code>string output_type = 3;</code>
     */
    protected $output_type = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.MethodOptions options = 4;</code>
     */
    protected $options = null;
    /**
     * Identifies if client streams multiple client messages
     *
     * Generated from protobuf field <code>bool client_streaming = 5;</code>
     */
    protected $client_streaming = false;
    /**
     * Identifies if server streams multiple server messages
     *
     * Generated from protobuf field <code>bool server_streaming = 6;</code>
     */
    protected $server_streaming = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $input_type
     *           Input and output type names.  These are resolved in the same way as
     *           FieldDescriptorProto.type_name, but must refer to a message type.
     *     @type string $output_type
     *     @type \Google\Protobuf\MethodOptions $options
     *     @type bool $client_streaming
     *           Identifies if client streams multiple client messages
     *     @type bool $server_streaming
     *           Identifies if server streams multiple server messages
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Input and output type names.  These are resolved in the same way as
     * FieldDescriptorProto.type_name, but must refer to a message type.
     *
     * Generated from protobuf field <code>string input_type = 2;</code>
     * @return string
     */
    public function getInputType()
    {
        return $this->input_type;
    }

    /**
     * Input and output type names.  These are resolved in the same way as
     * FieldDescriptorProto.type_name, but must refer to a message type.
     *
     * Generated from protobuf field <code>string input_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInputType($var)
    {
        GPBUtil::checkString($var, True);
        $this->input_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string output_type = 3;</code>
     * @return string
     */
    public function getOutputType()
    {
        return $this->output_type;
    }

    /**
     * Generated from protobuf field <code>string output_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOutputType($var)
    {
        GPBUtil::checkString($var, True);
        $this->output_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.MethodOptions options = 4;</code>
     * @return \Google\Protobuf\MethodOptions
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.MethodOptions options = 4;</code>
     * @param \Google\Protobuf\MethodOptions $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\MethodOptions::class);
        $this->options = $var;

        return $this;
    }

    /**
     * Identifies if client streams multiple client messages
     *
     * Generated from protobuf field <code>bool client_streaming = 5;</code>
     * @return bool
     */
    public function getClientStreaming()
    {
        return $this->client_streaming;
    }

    /**
     * Identifies if client streams multiple client messages
     *
     * Generated from protobuf field <code>bool client_streaming = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setClientStreaming($var)
    {
        GPBUtil::checkBool($var);
        $this->client_streaming = $var;

        return $this;
    }

    /**
     * Identifies if server streams multiple server messages
     *
     * Generated from protobuf field <code>bool server_streaming = 6;</code>
     * @return bool
     */
    public function getServerStreaming()
    {
        return $this->server_streaming;
    }

    /**
     * Identifies if server streams multiple server messages
     *
     * Generated from protobuf field <code>bool server_streaming = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setServerStreaming($var)
    {
        GPBUtil::checkBool($var);
        $this->server_streaming = $var;

        return $this;
    }

}

