<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

declare(strict_types=1);

namespace {{ namespace }};

interface {{ class }}Interface
{
{% for field in fields %}

    /**
     * @return {{ field.doc.output }}
     */
    public function get{{ field.name }}(): {{ field.type }};

    /**
     * @param {{ field.doc.input }} $value
     * @return void
     */
    public function set{{ field.name }}({{ field.type }} $value): void;
{% endfor %}
}
