<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace {{ namespace }};

/**
 * Autogenerated description for {{ class }} interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface {{ class }}Interface
{
{% for field in fields %}
    {% if field.simple %}
    /**
     * Autogenerated description for get{{ field.name }}() interface method
     *
     * @return {{ field.doc.output }}
     */
    public function get{{ field.name }}(): {{ field.type }};

    {% else %}
    /**
     * Autogenerated description for get{{ field.name }}() interface method
     *
     * @return {{ field.doc.output }}|null
     */
    public function get{{ field.name }}(): ?{{ field.type }};

    {% endif%}
    /**
     * Autogenerated description for set{{ field.name }}() interface method
     *
     * @param {{ field.doc.input }} $value
     * @return void
     */
    public function set{{ field.name }}({{ field.type }} $value): void;

{% endfor %}
}
