<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace {{ namespace }};

{% for import in imports %}
use {{ import }};
{% endfor %}

/**
 * Autogenerated description for {{ name }} class
 */
class {{ name }} implements {{ interface }}
{
    /**
     * @var {{ serverInterface }}
     */
    private $service;

    /**
     * @param {{ serverInterface }} $service
     */
    public function __construct(
        {{ serverInterface }} $service
    ) {
        $this->service = $service;
    }
{% for method in methods %}

    /**
     * Autogenerated description for {{ method.name }} in memory client service method
     *
     * @param {{ method.input.type }} $request
     * @return {{ method.output.type }}
     */
    public function {{ method.name }}({{ method.input.type }} $request): {{ method.output.type }}
    {
        return $this->service->{{ method.name }}($request);
    }
{% endfor %}
}
