<?xml version="1.0"?>
<!--
Generated by the Magento PHP proto generator.  DO NOT EDIT!
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="{{ module.name }}" />
</config>
