<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

declare(strict_types=1);

use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(ComponentRegistrar::MODULE, '{{ module.name }}', __DIR__);
