<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace {{ namespace }};

{% for method in methods %}
use {{ method.input.interface|split('\\', 2)[1] }};
use {{ method.output.interface|split('\\', 2)[1] }};
{% endfor %}

/**
 * Autogenerated description for {{ name }} interface
 */
interface {{ name }}
{
{% for method in methods %}
{% set methodInputInterfaceName = method.input.interface|split('\\')|last %}
{% set methodOutputInterfaceName = method.output.interface|split('\\')|last %}
    /**
     * Autogenerated description for {{ method.name }} interface method
     *
     * @param {{ methodInputInterfaceName }} $request
     * @return {{ methodOutputInterfaceName }}
     */
    public function {{ method.name }}({{ methodInputInterfaceName }} $request): {{ methodOutputInterfaceName }};

{% endfor %}
}
