<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace {{ namespace }};

{% for import in imports %}
use {{ import }};
{% endfor %}

/**
 * Autogenerated description for {{ name }} interface
 */
interface {{ name }}
{
{% for method in methods %}
    /**
     * Autogenerated description for {{ method.name }} interface method
     *
     * @param {{ method.input.type }} $request
     * @return {{ method.output.type }}
     * @throws \Throwable
     */
    public function {{ method.name }}({{ method.input.type }} $request): {{ method.output.type }};

{% endfor %}
}
