<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace {{ namespace }};

{% for import in imports %}
use {{ import }};
{% endfor %}
{% for import in protoImports %}
use {{ import }};
{% endfor %}

/**
 * Autogenerated description for {{ name }} class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
class {{ name }} implements {{ interface }}
{
    /**
     * @var {{ serverInterface }}
     */
    private $service;

    /**
     * @param {{ serverInterface }} $service
     */
    public function __construct(
        {{ serverInterface }} $service
    ) {
        $this->service = $service;
    }

{% for method in methods %}
    /**
     * Autogenerated description for {{ method.name }} method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param {{ method.proto.input }} $in
     * @return {{ method.proto.output }}
     */
    public function {{ method.name }}(\Spiral\GRPC\ContextInterface $ctx, {{ method.proto.input }} $in): {{ method.proto.output }}
    {
        try {
            $magentoDtoRequest = $this->{{ method.name }}FromProto($in);
            $magentoDtoResponse = $this->service->{{ method.name }}($magentoDtoRequest);
            return $this->{{ method.name }}ToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for {{ method.name }} method
     *
     * @param {{ method.proto.input }} $value
     * @return {{ method.input.type }}
     */
    private function {{ method.name }}FromProto({{ method.proto.input }} $value): {{ method.input.type }}
    {
        {{ method.input.fromProtoContent|raw }}

        return $out;
    }

    /**
     * Autogenerated description for {{ method.name }} method
     *
     * @param {{ method.output.type }} $value
     * @return {{ method.proto.output }}
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function {{ method.name }}ToProto({{ method.output.type }} $value): {{ method.proto.output }}
    {
        {{ method.output.toProtoContent|raw }}

        return $proto;
    }

{% endfor %}
}
